# Generated by Django 5.2.5 on 2025-09-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=100)),
            ],
        ),
    ]
